spring.application.name=papeleria
# 1. URL de conexión (cambia "papeleria_theoffice" por el nombre que le diste en phpMyAdmin)
spring.datasource.url=jdbc:mysql://localhost:3306/papeleria_theoffice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

#2. Credenciales
spring.datasource.username=root
spring.datasource.password=

# 3. Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Estrategia de Hibernate (¡Clave para la primera ejecución!)
# "update" creará las tablas si no existen y actualizará la estructura sin borrar tus datos de prueba.
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola para tener trazabilidad
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true